name: Create Branch on Comment

on:
  issue_comment:
    types: [created]

jobs:
  create-branch:
    if: startsWith(github.event.comment.body, '/create-branch')
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Get issue details
      id: issue
      run: |
        echo "title=${{ github.event.issue.title }}" >> $GITHUB_ENV
        echo "number=${{ github.event.issue.number }}" >> $GITHUB_ENV

    - name: Generate branch name
      id: generate_branch_name
      run: |
        ISSUE_TITLE="${{ env.title }}"
        ISSUE_NUMBER="${{ env.number }}"
        BRANCH_NAME="planit-${ISSUE_NUMBER}-$(echo "$ISSUE_TITLE" | tr -cd '[:alnum:]-' | tr ' ' '-')"
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Create new branch
      env:
        GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
      run: |
        BRANCH_NAME="${{ env.branch_name }}"
        git config --global user.name "mehrdad mahdian"
        git config --global user.email "mahdian.mhd@gmail.com"
        git fetch origin
        git checkout -b "$BRANCH_NAME"
        git push https://mehrdadmahdian:{{secrets.ACTION_TOKEN}}@github.com/mehrdadmahdian/test-token-for-workflow "$BRANCH_NAME"
