name: Create Branch on Comment

on:
  issue_comment:
    types: [created]

jobs:
  create-branch:
    if: startsWith(github.event.comment.body, '/create-branch')
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.NEW_ACTION_TOKEN }}

    - name: Get issue details
      id: issue
      run: |
        echo "title=${{ github.event.issue.title }}" >> $GITHUB_ENV
        echo "number=${{ github.event.issue.number }}" >> $GITHUB_ENV

    - name: Get existing branches
      id: branches
      run: |
        BRANCH_NAME="API-${ISSUE_NUMBER}-$(echo "$ISSUE_TITLE" | tr -cd '[:alnum:]-' | tr ' ' '-')"
        echo "Base branch name: $BRANCH_NAME"
        git fetch --all
        EXISTING_BRANCHES=$(git branch -r | grep "origin/$BRANCH_NAME" | sed 's/.*\///')
        echo "Existing branches: $EXISTING_BRANCHES"
        echo "::set-output name=existing_branches::$EXISTING_BRANCHES"

    - name: Determine new branch name
      id: new-branch
      run: |
        BASE_BRANCH_NAME="API-${ISSUE_NUMBER}-$(echo "$ISSUE_TITLE" | tr -cd '[:alnum:]-' | tr ' ' '-')"
        EXISTING_BRANCHES="${{ steps.branches.outputs.existing_branches }}"
        if [[ -z "$EXISTING_BRANCHES" ]]; then
          NEW_BRANCH_NAME="$BASE_BRANCH_NAME"
        else
          MAX=0
          for BRANCH in $EXISTING_BRANCHES; do
            if [[ "$BRANCH" =~ $BASE_BRANCH_NAME-([0-9]+)$ ]]; then
              NUM=${BASH_REMATCH[1]}
              if [[ $NUM -gt $MAX ]]; then
                MAX=$NUM
              fi
            fi
          done
          NEW_BRANCH_NAME="$BASE_BRANCH_NAME-$((MAX + 1))"
        fi
        echo "New branch name: $NEW_BRANCH_NAME"
        echo "::set-output name=new_branch_name::$NEW_BRANCH_NAME"

    - name: Create new branch
      env:
        GITHUB_TOKEN: ${{ secrets.NEW_ACTION_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        NEW_BRANCH_NAME="${{ steps.new-branch.outputs.new_branch_name }}"
        git checkout -b $NEW_BRANCH_NAME
        git push origin $NEW_BRANCH_NAME
