name: Create Branch on Comment

on:
  issue_comment:
    types: [created]

jobs:
  create-branch:
    if: startsWith(github.event.comment.body, '/create-branch')
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.NEW_ACTION_TOKEN }}

    - name: Get issue details
      id: issue
      run: |
        echo "title=${{ github.event.issue.title }}" >> $GITHUB_ENV
        echo "number=${{ github.event.issue.number }}" >> $GITHUB_ENV

    - name: Get existing branches
      env:
        GITHUB_TOKEN: ${{ secrets.NEW_ACTION_TOKEN }}
      run: |
        git fetch --all
        BASE_BRANCH_NAME="API-${{env.number}}-$(echo "${{env.title}}" | tr -cd '[:alnum:]-' | tr ' ' '-')"
        EXISTING_BRANCHES=$(git branch -r | grep "origin/$BASE_BRANCH_NAME" | sed 's/.*\///')
        if [[ -z "$EXISTING_BRANCHES" ]]; then
          NEW_BRANCH_NAME="$BASE_BRANCH_NAME"
        else
          MAX=0
          for BRANCH in $EXISTING_BRANCHES; do
            if [[ "$BRANCH" =~ $BASE_BRANCH_NAME-([0-9]+)$ ]]; then
              NUM=${BASH_REMATCH[1]}
              if [[ $NUM -gt $MAX ]]; then
                MAX=$NUM
              fi
            fi
          done
          NEW_BRANCH_NAME="$BASE_BRANCH_NAME-$((MAX + 1))"
        fi
        echo "New branch name: $NEW_BRANCH_NAME"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b $NEW_BRANCH_NAME
        git push origin $NEW_BRANCH_NAME
